### ISSUE TITLE
[Discussion] How can one restart Sella calculation ?

### ISSUE THREAD

**Issue by QuantumMisaka** [zadorlab/sella#49]
As title.

**Comment by juditzador** [comment]
In general, you just take the last geometry in your Sella calculation and use that as the starting point for a next round of optimizations. It can be a last geometry that was produced because Sella run out of steps, or perhaps your computer or the calculator crashed. But the last geometry is in the input file that Sella prepared last for the quantum chemistry program. Alternatively, you can run Sella with custom stopping criteria:
```
opt = Sella(atoms, ...)
for i in opt.irun(fmax=0):
    if custom_convergence_criteria(atoms):
        break
``` 
and in the for loop you can save or print the geometries for each step, which can then be reused upon restart.

**Comment by QuantumMisaka** [comment]
Thanks for reply!
As I understand ,sella is using finite difference method to generate initial Hessian information, can one use the stored Trajectroy file to restart the Hessian generate process (which is always the most time-comsuming step)? Or is there another way (rather than re-run Sella in the last geometry)

**Comment by juditzador** [comment]
If you have the full Hessian, you can read it in, see #19 

You can also save the trajectory file during the run, see #22  , which in principle has everything one may need, but unfortunately we don't have the utility at the moment to read that back in on a restart.
